### ISSUE TITLE
TakePhotoAsync not working on iPhone with OS >10

### ISSUE THREAD

**Issue by fcogutierrez** [jamesmontemagno/MediaPlugin#116]
I am testing the method: 

            var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
            {
                DefaultCamera = CameraDevice.Rear,
                SaveToAlbum = true
            });

In my iPhone6 with OS 10.1 and is it not working. The app breaks.

Any workaround to make this work?
Thanks in advance :)

**Comment by jamesmontemagno** [comment]
Was it working on 10.0?

Did you specify the new info.Plist information?

What exactly are you seeing?

**Comment by proxymus89** [comment]
I think that I've same problem since this morning.

I'm working with Xamarin and plugin media on an App since August with no problems. Yesterday I've build my solution to create Ios installer file (.ipa) and installed it on Iphone 6 of "user A" (actually i don't know his Ios version). All work perfectly. Today I rebuild solution (same code,same library, no modification) and installed on another iphone's user ("user B",allways iphone 6), but app crash when user try to open camera. I've tried to reinstall App to the other iphone (user A) with this last build and now also user A has same problem.

Only thing i noticed is that this morning when I open Xcode seems it download and install some updates.

**Comment by proxymus89** [comment]
Tomorrow i will check better, now i'm looking for on the web and I find that Xcode 8.1 was released yesterday.

Could be possible that new Xcode version 8.1 "Brokes" TakePhotoAsync method?

@fcogutierrez What is your Xcode version?

**Comment by jamesmontemagno** [comment]
It is recommend that you not upgrade to Xcode 8.1 yet unless you have the new new stable that just came out: https://releases.xamarin.com/stable-release-cycle-8-service-release-0-w-xcode8-1-support/

**Comment by jamesmontemagno** [comment]
When I get home I will first test:

iOS 10.1 on iPhone with Xcode 8.0

then I will test out iOS 10.1 with Xcode 8.1

See where and if it lives somewhere.

**Comment by proxymus89** [comment]
Ok I'm come back to work and my "User A" has:

Ios 10.0.2, no upgrade in last days

So problem should be Xcode 8.1

**Comment by fcogutierrez** [comment]
Ok it works. I just updated the plugin to last version and updated the ininfo.plist with the permissions:

```
<key>NSCameraUsageDescription</key>
<string>This app needs access to the camera to take photos.</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>This app needs access to photos.</string>
```

**Comment by proxymus89** [comment]
Problem is solved with "User A" after add

  <key>NSCameraUsageDescription</key>
  <string>This app needs access to the camera to take photos.</string>
  <key>NSPhotoLibraryUsageDescription</key>
  <string>This app needs access to photos.</string>

to info.plist

This have sense because I've seen that these lines are required to give permission to use your camera

What makes no sense is that until Monday, everything worked even without these lines (And "User A" was allways on Ios 10.0.2)

**Comment by proxymus89** [comment]
Eheh write at same time @fcogutierrez  :)

**Comment by fcogutierrez** [comment]
hahaha yes I saw @proxymus89 :)

Thanks for the support @jamesmontemagno this plugin is fantastic :)

**Comment by jamesmontemagno** [comment]
:) yup this is documented under: https://github.com/jamesmontemagno/MediaPlugin/blob/master/README.md#important-permission-information

I have added an example of what needs to be added. This is a change with xcode 8 and ios 10 in general

**Comment by proxymus89** [comment]
When I started to develop my application (august) I read documentation and these two keys did not exist because Ios 10 not existed :) last night i read again documentation and found that I had to add these two keys so I solved :)

**Comment by jamesmontemagno** [comment]
Yeah apple really threw everyone for a loop on this.

**Comment by saarthchitale** [comment]
Hey James! I am a novice in the world of programming, so maybe this might sounds like a silly question. I tried out the plugin for Android and it works absolutely fine. However, I am not able to call the crossmedia.current from iOS (On android, I simple call the method in OnCreate on the MainActivity page). I guess, that is the reason I keep getting "Oops! No camera" message when I run iOS app. Could you direct me to relevant documentation or tell me how to do it?

**Comment by DamonWick** [comment]
Hey James first of all thanks for the plugin 3.1.1 it's working smooth on android but in ios i am facing a problem i am using a shared code and the camera works fine on the initial launch of the code for both photo and video but on the second time it just get stuck at store media camera options and if i again open camera it throws an exception of only one camera operation can be working at a time. Any suggestions please i am kind of in a deadlock here.
