### ISSUE TITLE
TakePhotoAsync and Camera app crash

### ISSUE THREAD

**Issue by robecon** [jamesmontemagno/MediaPlugin#126]
## Bug 

Version Number of Plugin: 2.6.0
Device Tested On: Samsung Galaxy S3, Nexus 5X, Acer A1-811
Simulator Tested On: VS Android Emulator (7" with Android 4.4)

### Expected Behavior
MediaFile returned when photo is accepted

### Actual Behavior
Camera app crashes when photo is accepted, TakePhotoAsync returns null.
This happens only if android:targetSdkVersion is specified in AndroidManifest.xml, if it's not specified, TakePhotoAsync works as expected. (I cannot remove that from manifest because PlayStore would not let me publish the new version app as it would be considered a downgrade).
Crash did occurr on Android 4.4, did not occurr on Android 7.

### Steps to reproduce the Behavior
Use TakePhotoAsync in an app when AndroidManifest contains minSdkVersion and targetSdkVersion (eg,: <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="24" /> ), take a photo and accept picture taken.

**Comment by jamesmontemagno** [comment]
Did you follow: https://github.com/jamesmontemagno/MediaPlugin#android-n

I assume you are also compiling against 24 and targeting 24, which is what I do in my tests and working well.

What is the crash that you are getting? Is there a stack trace you can paste on http://gist.github.com

**Comment by robecon** [comment]
Yes, I followed those instructions and I compile against 24 and target 24 (in my AndroidManifest i have: <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="24" /> ).
I don't have a stack trace because my app doesn't crash at all and no exception is thrown, it's the standard Camera app that crashes showing the "Unfortunately, Camera has stopped" alert after photo is taken and then accepted, then the TakePhotoAsync returns null. 
Camera crashes did occurr on Android 4.4 and not on Android 7, where everything works fine.
If I only remove android:targetSdkVersion="24" from manifest, without making any other changes, everything works fine on 4.4 too.

**Comment by jamesmontemagno** [comment]
Seems like there is something wrong with the camera application. You could look into logcat and the device logs with ddms to see what is going on. The app would crash if there was something wrong setup for Android N. If you have a small repro sample you can paste it here and I can test. Have you tried it in a google emulator as well for API 24?

**Comment by robecon** [comment]
Here is logcat taken after camera crash: https://gist.github.com/robecon/22bb9ce7e3fd7dee890ca5ed8df52ce8

Permissions on manifest are as follows:
	<uses-permission android:name="android.permission.READ_PHONE_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

**Comment by jamesmontemagno** [comment]
So the issue here is with the FileProvider that I documented. Can you create a gist of your AndroidManifest.xml and file_paths.xml

java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider

**Comment by robecon** [comment]
Here it is:
https://gist.github.com/robecon/5812d88b32668065133312708d2156f1

**Comment by marcb777** [comment]
I've been getting this issue too.  It seems to affect API < 21, only when you target API 24.

@robecon Removing `android:targetSdkVersion="24"` from the AndroidManifest.xml seems to fix it because this effectively means you are targeting your minSdkVersion (per https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#target) - and I assume your minSdkVersion is earlier than API24.  (I find Xamarin misleading, in that it seems to imply that removing the targetSdkVersion means you are targeting the latest SDK, not the minimum).

After a bit of investigation, the exception being thrown by the camera app was a permission exception:

`Permission Denial: opening provider android.support.v4.content.FileProvider`

According to this SO post, the fix is to explicitly grant URI permissions to the Camera app intent: http://stackoverflow.com/a/33652695

I've added a PR #128 that resolves the crash.
