### ISSUE TITLE
Only one operation can be active at at time

### ISSUE THREAD

**Issue by erossini** [jamesmontemagno/MediaPlugin#199]
Hi James,
I have a question for you. I've created a component for an image gallery. A user can take or pick up a picture and I'm using your control. For about one year nobody complain. In the last two weeks a strange problem came up: I'm receive this error:

> Only one operation can be active at at time

I think this means a user can take two picture at the same time (?). I invoke 
		
    public ICommand CameraCommand {
        get { return _cameraCommand ?? new Command(async () => 
                 await ExecuteCameraCommand(), () => CanExecuteCameraCommand()); }
    }

    public bool CanExecuteCameraCommand() {
        if (!initialized)
            InitMedia();

        if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
        {
            return false;
        }
        return true;
    }

    public async Task ExecuteCameraCommand() {
        if (!initialized)
	    InitMedia();

        var file = await CrossMedia.Current.TakePhotoAsync(
                        new Plugin.Media.Abstractions.StoreCameraMediaOptions() {
				CompressionQuality = 100,
				Directory = path,
				Name = Guid.NewGuid().ToString() + "_original",
        });

        // more code
    }

Can I have an advice for you about it? Thank you in advance!

**Comment by ericbrunner** [comment]
@erossini I respond because I have an open issue too here. Take a look on my gist: https://gist.github.com/ericbrunner/5a4c76cb5cbabc3a992c5a97a216c81c

I Had that problem, too in the past. I Happens when for example a PickAsync operation is started twice or a PickAsync and TakrAsync or a TakeAsync operation is started twice.

In short: Only one operation is allowed at the same time until the task finished.

I use a SemaphoreSlim lock to achieve exactly that. The SemaphoreSlim lock is configured to only allow one async operation at a time. Hope it helps you out.

**Comment by erossini** [comment]
@ericbrunner Thanks!

**Comment by ericbrunner** [comment]
@erossini You are welcome. Did it solve your issue?
