### ISSUE TITLE
[Feature Request] Choose album in PickPhotoAsync()

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#20]
_From @VincentVanWijk on March 18, 2016 11:1_

it would be very nice for me if i could choose an album to load pictures from in PickPhotoAsync() instead of always showing the entire gallery.

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#250_

**Comment by jamesmontemagno** [comment]
_From @VincentVanWijk on March 31, 2016 7:30_

is this even possible?

**Comment by WillAutioItrax** [comment]
We would find this quite useful. It seems odd that the app can save a picture to a new directory (which is really useful) but it can not view pictures in that directory (or am I missing something).

**Comment by clmorales** [comment]
I will find this really useful on an HIPAA app I am working on because I want the users to take pictures when they are offline to a custom directory (that feature is already in takepicture options), then when they are online be able to browse pictures from the same custom directory to upload those pictures and delete them after a success upload.

**Comment by jamesmontemagno** [comment]
No new features.
