### ISSUE TITLE
Multiple activities in recent apps (Only in samsung s7/edge7)

### ISSUE THREAD

**Issue by CarMatt** [jamesmontemagno/MediaPlugin#201]
## Bug 
Leavs a a second item in android recent list over apps
It applies only on Android with Samsung s7 / Edge7 with android 7.0… so far…

Version Number of Plugin: 2.6.2
Device Tested On:  Samsung s7/edge7 with android 7.0

### Expected Behavior
Only one item(Main app) in recent list after returning from camera or media library
### Actual Behavior
Left a "dead" item in recent application list
### Steps to reproduce the Behavior
Use CrossMedia.Current.TakePhotoAsync and return to main application

**Comment by jamesmontemagno** [comment]
Please add screenshot

**Comment by ericbrunner** [comment]
@CarMatt I had similar wired behaviour. Its not a Media Plugin issue, on my side. I started Media Plugin TakePhotoAsync / PickPhotoAsync Task from a second thread with Device.BeginInvokeOnMainThread. After removing that, I never had that issue again.

Can you post your code on gist.github.com and add a link here?

Because I use Media Plugin in an industrial app I am very interested in that issue, too.

**Comment by CarMatt** [comment]
I found a solution. To clarify, our main activity is set to singleinstance and to keep new activities as MediaPlugin(Camera/Gallery) in the same task, you need to set `TaskAffinity` = `""` on main activity. It applies only in Android > 7.0. We had no problems in previous versions.

To add, our main activity inherits from FormsApplicationActivity. If it is different from FormsAppCompatActivity, I do not know.
