### ISSUE TITLE
TakePhotoAsync take several minutes to go back to code

### ISSUE THREAD

**Issue by susanhenr** [jamesmontemagno/MediaPlugin#31]
When I call the function **TakePhotoAsync(...)** it takes several minutes there and image shows with delay on page.

If the image size is too big, it takes more time. Is there any way to tell the image size I want the photo store?

`                    StoreCameraMediaOptions cameraOptions = new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {

                        Directory = "VesselsPhotos",
                        Name = namePhotoVessel + ".jpg",
                        DefaultCamera = CameraDevice.Rear,
                        PhotoSize = PhotoSize.Small,
                    };
                    file = await CrossMedia.Current.TakePhotoAsync(cameraOptions);`

Thank you!

**Comment by jamesmontemagno** [comment]
Can you please fill in the issue form:
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

### Expected Behavior

### Actual Behavior

### Steps to reproduce the Behavior

**Comment by DennisWelu** [comment]
I came to look at the Issues list and noticed this one. I was seeing something similar although it didn't take minutes just maybe 10 seconds. So I pulled down source and traced through. The delay is all happening on this line: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaImplementation.cs#L187.

The way I'm reading the flow there is it's going to RotateImage, CompressAsync, and File.Open/Create for every image. The bigger the image, the longer it takes and seems like some unnecessary steps if the rotation is correct to begin with. 

Also I think the CompressAsync isn't actually compressing the image as its compressing to a PNG which is lossless. That's my current thought anyway...

Sound reasonable?

**Comment by jamesmontemagno** [comment]
I am thinking that we should change those to jpeg actually as they take some time. 

Does the open take a long time? or just the compress?

We could also try to wrap that in a Task.Run(()=>{}); Perhaps. I will try to go and debug this a bit.

**Comment by jamesmontemagno** [comment]
Checkout: 2.5.1-beta35

Compressing can still take time obviously, but it will not lock the UI thread.

**Comment by DennisWelu** [comment]
Just catching up with things. The move to a non-UI thread is a keeper. At least my activity indicator spins now. :-)

I'm also quite glad to see the compression quality as an option now. I was going to request that otherwise! Although it may be odd that the compression quality only applies when the image needs to be rotated or resized.

The only other observation I'd make, which is clearly an off-thread change request, is the Small/Medium/Large option for establishing a resize percent rough. I really need to be able to have more control on resizing. A percentage is a nice option...but optionally to specify a specific percent would be better. Also in my current app the resize needs to be specific resolution which the percentage approach does not handle, so I end up resizing after the photo is taken anyway. FWIW.

Thanks for the fix!
