### ISSUE TITLE
NullReferenceException - FormsAppCompatActivity.InternalSetPage

### ISSUE THREAD

**Issue by alwydl** [jamesmontemagno/MediaPlugin#434]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.6.2 and 3.1.1
Device Tested On: Zenfone 2
Simulator Tested On: none
Version of VS: 2015 Comunnity 3
Version of Xamarin: 4.8.188
Versions of other things you are using:

### Steps to reproduce the Behavior
Version previous to SDK 25 in android was working fine. After updated the SDK and Plugin version, it stopped working.
Using FormsAppCompatActivity in Android

### Expected Behavior
Not block the app and allow to use camera

### Actual Behavior
LoadApplication(new App) is giving the following exception:

System.NullReferenceException: Object reference not set to an instance of an object.
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage (Xamarin.Forms.Page page) [0x0005e] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:315 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:343 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication (Xamarin.Forms.Application application) [0x0025c] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:139 
  at Shappa.Droid.MainActivity+<OnCreate>d__0.MoveNext () [0x001b9] in C:\Andre\Shappa\Shappa\Shappa\Shappa.Droid\MainActivity.cs:62 

### Code snippet
https://gist.github.com/alwydl/e440f3e3745947ec4ad88597606a1a2f

### Screenshots
If I take out the initialization process added for this new version (override permission, assemblyInfo and manifest) it enters the App class, but the camera does not work.

**Comment by MichaelGiger** [comment]
I have the same issue!
Plugin Version 3.1.2

**Comment by jamesmontemagno** [comment]
What version of Xamarin.Forms? Probably a regression on their part.

**Comment by MichaelGiger** [comment]
Xamarin.Forms v2.5.0.122203

**Comment by MichaelGiger** [comment]
It works with Visual Studio v15.4.2!
It's not working on my local development computer. I have installed Visual Studio v15.5.3

**Comment by alwydl** [comment]
It was the latest Version of forms here too. But I`ve made a rollback and kept it downgraded for now.
My VS is 2015, 14.0.25431.01 update 3 (but I don`t think it is this)

**Comment by jamesmontemagno** [comment]
Should be reported against Xamarin.Forms or Xamarin.Android repos as it has nothing to do with the plugin that I can tell.

**Comment by HoGo72** [comment]
Actually I do have the same Problem.
TakeFotoAsnyc works on iOS and UWP but gives NullPointerException on Android
Installed NuGet-pkg:
MediaPlugIn 3.1.2
Xamarin.Android.... 26.1.0.1
Xamarin.Forms 2.5.0.129934
VS2017 15.5.3

I changed back to MediaPlugIn 3.1.1 and 3.0.1. Same result
I changed back to MediaPlugIn 3.1.2. 
And Changed Xamarin.Forms back to 2.5.0.122203 and 2.5.0.77107. Same result.

Changing back the Xamarin.Android-Packages from 26.1.0.1 back to 26.0.2 is impossible because of the cross dependencies. So I couldn't test this.

Meybe you could detect the Point where it's going wrong, fill a xamarin bug Report, post the link here so we can add our "me too"

Maybe you could also add some Information about which package/version causes the problem for Rollback

Best regards, Holger Gothan.

**Comment by PaulVrugt** [comment]
this happened to me to. Cleaning the solution, closing visual studio, deleting all obj and bin folder, restarting studio, rebuilding and trying again helped.

**Comment by Soarc** [comment]
Same here. Delete bin/obj, clean rebuild helped me too. 
Hope someday xamarin will be idempotent to rebuilds. :(

**Comment by developMediaSoft** [comment]
Hope you don't mind me updating this thread here, it's what the search engine turns reports for this error:
I found this error to be caused by a Resources/values/styles.xml file in my Xamarin.Android project, in particular I've resolved it by removing the "android:" prefix from each name attribute of each item node.

**Comment by wireless-r** [comment]
I came here from Google as well. For me it was solved by unchecking "Enable ProGuard" in Android options.

**Comment by MonkeyBrush** [comment]
See this Bug in Xamarin.  I had to downgrade from Xamarin.Android.Support.* versions 27.0.2 to 26.1.0.1.
https://bugzilla.xamarin.com/show_bug.cgi?id=36287

**Comment by PaulVrugt** [comment]
@developMediaSoft 

This seems to have fixed the issue for me too. I had an "android:textAllCaps" and "android:windowNoTitle" item in styles.xml, removing the "android:" from them seems to resolve the issue

**Comment by nbsoftware** [comment]
Same a @wireless-r , *just* unchecking "Enable Proguard" (not touching anything else) on release build did work around the issue.

**Comment by bruzkovsky** [comment]
This is an issue with X.F and it is tracked here: https://github.com/xamarin/Xamarin.Forms/issues/2148
