### ISSUE TITLE
Android: Zero byte image is getting saved in the device

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/MediaPlugin#66]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Nexus 9 Tablet Android 5.1.1  

### Expected Behavior
Should not have saved the captured image with zero bytes

### Actual Behavior
In Nexus devices, there is an option to close the camera(Apart from the option to Accept/Decline the captured Image). If the camera is closed then it will save a zero byte image in the device. 

### Steps to reproduce the Behavior
1. Load the application.
2. Tap on CameraCapture Button.
3. Capture an image -> Image should be captured with an option to cancel or accept/reject the image. In nexus, there is an option(3rd Option) to close the camera
4. If we select the 3rd option, camera is closed then it will save a zero byte image in the device. 

## Feature Request:
1. It should not save the zero byte image to device if we select the 3rd option to close the camera.
2. If it is saving the image, then the path of the image should be returned back to the API 
caller.

**Comment by pradeeparutla** [comment]
Hi James any update on this?

**Comment by jamesmontemagno** [comment]
I have not investigated it just yet, but on my radar.

**Comment by fabionuno** [comment]
Hi @jamesmontemagno this behavior occurs in all Android versions that I have tested (5.0.1, 5.1.1 and 6.0). 
This is because an empty file is intentionally created by the [`Touch method`](https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaPickerActivity.cs#L174) before the Camera Intent be started. 
If the user exits the Camera app without take a picture this file remains empty.

For testing purposes I removed the `Touch` method call and ran the MediaAndroidTest app in API21 and API23, in all cases the operation was successfully performed without create an empty file first.

I think we have two solutions to this bug:
We could simply delete the file created by `Touch` method if the Intent's `resultCode` is equal to Canceled, this will avoid unknown side effects caused by removing the Touch method;

Remove the `Touch` method without knowing why exactly it needs to be called, which may cause some other problem. This solution is more agressive but avoids unecessary file operations and the risk of orphaned files be created if the app crash before we have the opportunity to delete the empty file

What do you think?

**Comment by jamesmontemagno** [comment]
@fabionuno I am thinking option 1 is the best if we know the result code is canceled then we can safely try to delete it. That should work nicely.

**Comment by pradeeparutla** [comment]
Is it part of a stable build 2.6.0? It is still reproducible in  the latest release build

**Comment by SandeepChorge** [comment]
Hii, I am working on different project but same issue as **Zero byte image is getting saved in the device**. I am creating a file using **File.createTempFile** and triggering camera Intent using EXTRA_OUTPUT as extras, so what happen is whenever I capture image it does not update the existing file created temp file and size remains 0B, can you help me out?
