### ISSUE TITLE
Uploading multiple images on iOS 13.0

### ISSUE THREAD

**Issue by auratuk** [jamesmontemagno/MediaPlugin#755]
## Bug Information

Version Number of Plugin: 4.4.2-beta
Simulator Tested On: iPhone 11 13.0
Version of VS: 16.3.3
Version of Xamarin: 4.0.0

### Steps to reproduce the Behavior
1. Select images in a gallery
2. Press "Done" button

### Expected Behavior
Successful image uploading

### Actual Behavior
An exception occurs and an app crashes

### Screenshots
![image](https://user-images.githubusercontent.com/26546452/66720741-76fe3b80-ee09-11e9-8a00-5b63fac48b3d.png)

Meanwhile on Android everything seems to be OK.

**Comment by jamesmontemagno** [comment]
It could be that they finally killed the API that this was using. You could try 4.3.1-beta before I did refactoring and see if that makes any difference, however it may just no longer be supported I didn't write this code so will be tricky as it will require a full re-write.

**Comment by jamesmontemagno** [comment]
The same code does work on iOS 12 :( so looks like perhaps we will have to investigate this more.

**Comment by auratuk** [comment]
Thanks for a workaround it seems to be working fine

**Comment by IngweLand** [comment]
Not sure if this is the same reason, but if yes, then the issue is still present in 4.4.4-beta
iOS - 13.1.3
VS - 16.3.5
XF - 4.2.0

Happens when you use CrossMedia.Current.PickPhotosAsync. Select multiple photos then click Done. Then immediate crash.

I think this issue is related to iCloud photos. Before, iCloud photos were not visible in picker at all. Right now, they all are there. However, the crash happens when you select photos which originals are on the iCloud. When you take photos with regular Camera app, then immediately go to your app (which uses this library), then select those new photo(s) (so they are still a local files, not yet uploaded to iCloud), everything works.


Failed to set thumbnail System.ArgumentNullException: Value cannot be null.
Parameter name: cgImage
  at UIKit.UIImage..ctor (CoreGraphics.CGImage cgImage) [0x00042] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIImage.g.cs:137 
  at Plugin.Media.ELCImagePickerViewController+ELCAlbumPickerController.GetCell (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) [0x00061] in D:\a\1\s\src\Media.Plugin\iOS\ECLImagePickerViewController.cs:348

**Comment by auratuk** [comment]
Hmm... good point, I haven't tried uploading photos from iCloud..

**Comment by jamesmontemagno** [comment]
That is a different bug, please file it.
