### ISSUE TITLE
TakePhotoAsync causes crash from unmanaged code, can't catch, app crashes

### ISSUE THREAD

**Issue by daveblt** [jamesmontemagno/MediaPlugin#930]
## Bug Information

Version Number of Plugin: Xam.Plugin.Media 5.0.1 
Device Tested On: iPad 7th Generation, iOS 14.4.2
Simulator Tested On: N/A
Version of VS: VS Mac 8.9.4 (build 25)
Version of Xamarin: 5.0.0.2012
Versions of other things you are using: 

### Steps to reproduce the Behavior
Verify camera permissions, bring up camera via `await CrossMedia.Current.TakePhotoAsync`, take a picture and click "Use Photo".  App crashes, but not always.

### Expected Behavior
Call `await CrossMedia.Current.TakePhotoAsync` and get back media file or null.

### Actual Behavior
App crashes due to an exception in unmanaged code.  

### Code snippet
```
var status = await Permissions.CheckStatusAsync<Permissions.Camera>();

if (status != PermissionStatus.Granted || !CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported) { /* Abort. */ }

var options = new StoreCameraMediaOptions
{
    Directory = "Test",
    SaveToAlbum = false,
    CompressionQuality = 75,
    CustomPhotoSize = 50,
    PhotoSize = PhotoSize.MaxWidthHeight,
    MaxWidthHeight = 2000,
    DefaultCamera = CameraDevice.Rear,
    SaveMetaData = true,
    AllowCropping = false
};

MediaFile file = null;

try { file = await CrossMedia.Current.TakePhotoAsync(options); }
catch (Exception ex) { file = null; }
```

### Screenshots
See stack trace https://gist.github.com/daveblt/08a6991b8aa5ea606daf2444d52bb099

**Comment by aismaniotto** [comment]
I guess I have the same problem... Any workaround?

**Comment by daveblt** [comment]
The only thing to do is use Xamarin Essentials instead.  This library is abandoned.

**Comment by aismaniotto** [comment]
Actually, I have the same problem on Essentials too, the app crashs and don't stop on the catch (not even notify the appcenter)... very weard :/

**Comment by Brunoporto2702** [comment]
I am experiencing the same problem on Android 11! Does someone figured a workaround? 

Cheers!

**Comment by Awdos** [comment]
Same problem, any progress ?

**Comment by daveblt** [comment]
No, unfortunately there will never be any progress.  This plugin is abandoned.  Only solution is to switch to Xamarin.Essentials.

**Comment by Awdos** [comment]
So is there a problem with Xamarin.Essentials ?

**Comment by daveblt** [comment]
It works.  Really stupid how this plugin was abandoned and no notice was posted.

**Comment by Awdos** [comment]
@daveblt thank youu.

Could you please share the most performing and compatible code? It seems like it would be tiring to revise the code again.

**Comment by daveblt** [comment]
Here is the documentation page.
https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?tabs=ios

It really sucks that this plugin was abandoned without any notice to people about how to migrate.

**Comment by Awdos** [comment]
Thank you very much.

**Comment by Brunoporto2702** [comment]
Just sharing my experience, it might help someone....

I have recently migrated from CrossMedia to MediaPicker and I have been trough much more trouble than I expected... 

First of all, just to install the Xamarin.Essentials library, I had to migrate to androidX and d8 dex compiler in order to build the app again. 

after that, when I put everything to work again. I had to do some image processing (resizing and rotating the pictures taken) to do in order that everything worked smoothly. Otherwise, the picture taken would be sideways and too large. 

I am currently testing with some users to see if the white screen intermitent error stops for good. Once I get the results, I'll come here share with you! 

cheers

**Comment by Awdos** [comment]
Thanks for sharing your experiences! I switched from CrossMedia to MediaPicker, but when the camera page is opened, my application automatically terminates and does not give any errors. I need all kinds of help.

We're going through some very silly things.

**Comment by Awdos** [comment]
I still have the same problem when the camera is turned on. Could you please share your code? @daveblt

**Comment by fvalentiner** [comment]
We've had this issue for the last 6 months. Last week we found [this tutorial](http://www.nuget.org/packages/Xam.Plugin.Media) . After we set up Plugin.CurrentActivity plugin for Media Plugin to attach itself to the active Activity during the run time. And like magic, no more crashes. We believe that since it is attached to the activity, android does not mess with it.

Hope it helps fix the issue for other people.

**Comment by SilvioLuizGuimaraes** [comment]
I have 45 days trying to solve it and nothing, @fvalentiner your link is broken with resolution.

**Comment by jamesmontemagno** [comment]
Unable to reproduce on iOS here with the sample in the repo and latest beta

**Comment by Awdos** [comment]
@jamesmontemagno any solution?

**Comment by gshri67** [comment]
@All 

On digging deeper, i found that this issue happens when the picture is taken from rear camera and it doesn't occur when the picture is taken from front camera..

Could be that, it is trying to draw a larger bitmap when picture is taken from rear camera, and same causes a memory leak issue..

@jamesmontemagno please help us here..
